# for development

services:
  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080
    environment:
      BROWSER: none
      PORT: 8080
    command: sh -c 'npm i && npm start'