# for development

services:
  frontend:
    image: node:16
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - 8080:8080
    environment:
      BROWSER: none
      PORT: 8080
    command: sh -c 'npm i && npm start'

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8081:8081
    environment:
      LOG_LEVEL: DEBUG
      CORS_ALLOW_ORIGIN: http://localhost:8080
    command: adev runserver --port 8081 .